// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCpDxjO0QIw7hgCeA-mytYeNxfZ6qmg8yM',
    appId: '1:565408411342:web:8a687e40c5094b4f532a9f',
    messagingSenderId: '565408411342',
    projectId: 'food-delivery-app-229f6',
    authDomain: 'food-delivery-app-229f6.firebaseapp.com',
    storageBucket: 'food-delivery-app-229f6.appspot.com',
    measurementId: 'G-FH88CZX5K6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB46aJPH8bp-td4vX68Rgou5mz3gwEBWZc',
    appId: '1:565408411342:android:dab4b1c892d1992f532a9f',
    messagingSenderId: '565408411342',
    projectId: 'food-delivery-app-229f6',
    storageBucket: 'food-delivery-app-229f6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAkbBqmBuAJua41TbVvMGyDS-ivxUjs_HA',
    appId: '1:565408411342:ios:86e89dc84d7fd914532a9f',
    messagingSenderId: '565408411342',
    projectId: 'food-delivery-app-229f6',
    storageBucket: 'food-delivery-app-229f6.appspot.com',
    iosBundleId: 'com.example.foodApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAkbBqmBuAJua41TbVvMGyDS-ivxUjs_HA',
    appId: '1:565408411342:ios:86e89dc84d7fd914532a9f',
    messagingSenderId: '565408411342',
    projectId: 'food-delivery-app-229f6',
    storageBucket: 'food-delivery-app-229f6.appspot.com',
    iosBundleId: 'com.example.foodApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCpDxjO0QIw7hgCeA-mytYeNxfZ6qmg8yM',
    appId: '1:565408411342:web:e3fb6459b92449ed532a9f',
    messagingSenderId: '565408411342',
    projectId: 'food-delivery-app-229f6',
    authDomain: 'food-delivery-app-229f6.firebaseapp.com',
    storageBucket: 'food-delivery-app-229f6.appspot.com',
    measurementId: 'G-Z1WHGFTQLZ',
  );
}
